name: Repository CI Pipelines

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint with clang-format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1

    - name: Run clang-format
      run: |
        chmod +x format_check.sh ; ./format_check.sh
    
  unit_test:
    name: Run Native Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmake-version: '3.27'

    - name: Configure CMake for testing
      run: |
        cmake --preset=native -DTARGET_APP="" -DCMAKE_BUILD_TYPE="Debug"

    - name: Build GTest unit tests
      run: cd build/ && cmake --build .

    - name: Run GTest unit tests
      run: ctest