name: Repository CI Pipelines

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint with clang-format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1

    - name: Run clang-format
      run: |
        chmod +x format_check.sh ; ./format_check.sh
  
  Build:
    name: Build Embedded
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmake-version: '3.27'
    
    - name: Pull git submodules
      run: |
        git submodule update --init --recursive
    
    - name: Install GNU Arm Embedded Toolchain
      uses: ryanwinter/arm-none-eabi-gcc@master
        with:
          release: '10.3-2021.10'

    - name: Configure CMake for F7
      run: |
        cmake --preset=stm32f746 -DTARGET_APP="" -DCMAKE_BUILD_TYPE="Debug"

    - name: Build for F7
      run: cd build/ && cmake --build .
    
    - name: Configure CMake for H5
      run: |
        rm -rf build/ && cmake --preset=stm32h503 -DTARGET_APP="" -DCMAKE_BUILD_TYPE="Debug"

    - name: Build for H5
      run: cd build/ && cmake --build .
    
    - name: Configure CMake for L4
      run: |
        rm -rf build/ && cmake --preset=stm32hl476 -DTARGET_APP="" -DCMAKE_BUILD_TYPE="Debug"

    - name: Build for L4
      run: cd build/ && cmake --build .
    
  unit_test:
    name: Run Native Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmake-version: '3.27'
    
    - name: Pull git submodules
      run: |
        git submodule update --init --recursive

    - name: Configure CMake for testing
      run: |
        cmake --preset=native -DTARGET_APP="" -DCMAKE_BUILD_TYPE="Debug"

    - name: Build GTest unit tests
      run: cd build/ && cmake --build .

    - name: Run GTest unit tests
      run: cd build/ && ctest